# Generated by Django 5.1.11 on 2025-08-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the campaign', max_length=255, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the campaign was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the campaign was last updated', verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
