# Generated by Django 5.1.11 on 2025-08-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_number', models.CharField(help_text='The company registration number', max_length=20, verbose_name='Company Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the company number was added', verbose_name='Created at')),
                ('campaign', models.ForeignKey(help_text='The campaign this company number belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='company_numbers', to='portal.campaign')),
            ],
            options={
                'verbose_name': 'Company Number',
                'verbose_name_plural': 'Company Numbers',
                'ordering': ['company_number'],
            },
        ),
    ]
