# Generated by Django 5.1.11 on 2025-08-11 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_companydetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHouseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
                ('company_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Status')),
                ('company_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Type')),
                ('incorporation_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='Incorporation Date')),
                ('jurisdiction', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jurisdiction')),
                ('registered_office_address', models.TextField(blank=True, null=True, verbose_name='Registered Office Address')),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('locality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Locality')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Region')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('registered_office_is_in_dispute', models.CharField(blank=True, max_length=10, null=True, verbose_name='Registered Office Is In Dispute')),
                ('undeliverable_registered_office_address', models.CharField(blank=True, max_length=10, null=True, verbose_name='Undeliverable Registered Office Address')),
                ('sic_codes', models.TextField(blank=True, null=True, verbose_name='SIC Codes')),
                ('can_file', models.CharField(blank=True, max_length=10, null=True, verbose_name='Can File')),
                ('has_been_liquidated', models.CharField(blank=True, max_length=10, null=True, verbose_name='Has Been Liquidated')),
                ('has_charges', models.CharField(blank=True, max_length=10, null=True, verbose_name='Has Charges')),
                ('has_insolvency_history', models.CharField(blank=True, max_length=10, null=True, verbose_name='Has Insolvency History')),
                ('previous_company_names', models.TextField(blank=True, null=True, verbose_name='Previous Company Names')),
                ('last_accounts_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='Last Accounts Date')),
                ('last_accounts_period_start', models.CharField(blank=True, max_length=20, null=True, verbose_name='Last Accounts Period Start')),
                ('last_accounts_period_end', models.CharField(blank=True, max_length=20, null=True, verbose_name='Last Accounts Period End')),
                ('last_accounts_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Accounts Type')),
                ('next_accounts_due', models.CharField(blank=True, max_length=20, null=True, verbose_name='Next Accounts Due')),
                ('next_accounts_period_end', models.CharField(blank=True, max_length=20, null=True, verbose_name='Next Accounts Period End')),
                ('accounts_overdue', models.CharField(blank=True, max_length=10, null=True, verbose_name='Accounts Overdue')),
                ('accounting_reference_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='Accounting Reference Date')),
                ('confirmation_statement_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='Confirmation Statement Date')),
                ('confirmation_statement_next_due', models.CharField(blank=True, max_length=20, null=True, verbose_name='Confirmation Statement Next Due')),
                ('confirmation_statement_overdue', models.CharField(blank=True, max_length=10, null=True, verbose_name='Confirmation Statement Overdue')),
                ('officers_total_count', models.CharField(blank=True, max_length=10, null=True, verbose_name='Officers Total Count')),
                ('officers_active_count', models.CharField(blank=True, max_length=10, null=True, verbose_name='Officers Active Count')),
                ('officers_resigned_count', models.CharField(blank=True, max_length=10, null=True, verbose_name='Officers Resigned Count')),
                ('officers_inactive_count', models.CharField(blank=True, max_length=10, null=True, verbose_name='Officers Inactive Count')),
                ('key_officers', models.TextField(blank=True, null=True, verbose_name='Key Officers')),
                ('last_full_members_list_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='Last Full Members List Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('INVALID_COMPANY_NUMBER', 'INVALID_COMPANY_NUMBER'), ('COMPANY_NOT_FOUND', 'COMPANY_NOT_FOUND'), ('API_ERROR', 'API_ERROR'), ('EXTRACTION_ERROR', 'EXTRACTION_ERROR'), ('RATE_LIMIT_ERROR', 'RATE_LIMIT_ERROR')], default='SUCCESS', max_length=30, verbose_name='Status')),
                ('company_number', models.OneToOneField(help_text='The company number this detail belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='house_data', to='portal.companynumber')),
            ],
            options={
                'verbose_name': 'Company House Data',
                'verbose_name_plural': 'Company House Data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CompanyDetail',
        ),
    ]
