# Generated by Django 5.1.11 on 2025-08-11 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_companyhousedata_delete_companydetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='VAT Number')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
                ('search_terms', models.TextField(blank=True, help_text='Search terms that were tried', null=True, verbose_name='Search Terms')),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('INVALID_COMPANY_NAME', 'INVALID_COMPANY_NAME'), ('VAT_NOT_FOUND', 'VAT_NOT_FOUND'), ('SERVICE_BLOCKED', 'SERVICE_BLOCKED'), ('NETWORK_ERROR', 'NETWORK_ERROR'), ('PARSING_ERROR', 'PARSING_ERROR'), ('MULTIPLE_RESULTS_NO_MATCH', 'MULTIPLE_RESULTS_NO_MATCH')], default='SUCCESS', max_length=30, verbose_name='Status')),
                ('processing_notes', models.TextField(blank=True, null=True, verbose_name='Processing Notes')),
                ('proxy_used', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proxy Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('company_number', models.OneToOneField(help_text='The company number this VAT data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='vat_data', to='portal.companynumber')),
            ],
            options={
                'verbose_name': 'VAT Lookup',
                'verbose_name_plural': 'VAT Lookups',
                'ordering': ['-created_at'],
            },
        ),
    ]
