# Generated by Django 5.1.11 on 2025-08-11 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_vatlookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatlookup',
            name='company_number',
            field=models.OneToOneField(help_text='The company number this VAT data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='vat_lookup', to='portal.companynumber'),
        ),
    ]
