# Generated by Django 5.1.11 on 2025-08-11 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_vatlookup_company_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Domain to blacklist from website crawling (e.g., example.com)', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_domain', message='Enter a valid domain name (e.g., example.com)', regex='^([a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?\\.)+[a-zA-Z]{2,}$')], verbose_name='Domain')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Blacklist Domain',
                'verbose_name_plural': 'Blacklist Domains',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='SERPExcludedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Domain to exclude from SERP results (e.g., example.com)', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_domain', message='Enter a valid domain name (e.g., example.com)', regex='^([a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?\\.)+[a-zA-Z]{2,}$')], verbose_name='Domain')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'SERP Excluded Domain',
                'verbose_name_plural': 'SERP Excluded Domains',
                'ordering': ['domain'],
            },
        ),
    ]
