# Generated by Django 5.1.11 on 2025-08-11 15:51

from django.db import migrations


def add_default_serp_excluded_domains(apps, schema_editor):
    """
    Add default SERP excluded domains.
    """
    SERPExcludedDomain = apps.get_model('portal', 'SERPExcludedDomain')
    
    # Default domains to exclude from SERP results
    default_domains = [
        "gov.uk",
        "endole.co.uk",
        "pappers.fr",
        "opencorporates.com",
        "company-information.service.gov.uk",
        "ebay.co.uk",
        "amazon.co.uk",
        "checkcompany.co.uk",
        "find-and-update.company-information.service.gov.uk",
        "bizstats.co.uk",
        "globaldatabase.com",
        "duedil.com",
        "chostar.co.uk",
        "britishlei.co.uk",
        "vat-lookup.co.uk"
    ]
    
    # Add each domain if it doesn't already exist
    for domain in default_domains:
        SERPExcludedDomain.objects.get_or_create(domain=domain)


def remove_default_serp_excluded_domains(apps, schema_editor):
    """
    Remove default SERP excluded domains (for rollback).
    """
    SERPExcludedDomain = apps.get_model('portal', 'SERPExcludedDomain')
    
    default_domains = [
        "gov.uk",
        "endole.co.uk",
        "pappers.fr",
        "opencorporates.com",
        "company-information.service.gov.uk",
        "ebay.co.uk",
        "amazon.co.uk",
        "checkcompany.co.uk",
        "find-and-update.company-information.service.gov.uk",
        "bizstats.co.uk",
        "globaldatabase.com",
        "duedil.com",
        "chostar.co.uk",
        "britishlei.co.uk",
        "vat-lookup.co.uk"
    ]
    
    # Remove each default domain
    SERPExcludedDomain.objects.filter(domain__in=default_domains).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_blacklistdomain_serpexcludeddomain'),
    ]

    operations = [
        migrations.RunPython(add_default_serp_excluded_domains, remove_default_serp_excluded_domains),
    ]
