# Generated by Django 5.1.11 on 2025-08-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_add_default_serp_excluded_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZenSERPQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_credits', models.PositiveIntegerField(default=0, help_text='Number of available ZenSERP API credits', verbose_name='Available Credits')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When the quota was last updated', verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'ZenSERP Quota',
                'verbose_name_plural': 'ZenSERP Quota',
            },
        ),
    ]
