# Generated by Django 5.1.11 on 2025-08-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_zenserpquota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhousedata',
            name='accounts_overdue',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Accounts Overdue'),
        ),
        migrations.AlterField(
            model_name='companyhousedata',
            name='can_file',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Can File'),
        ),
        migrations.AlterField(
            model_name='companyhousedata',
            name='confirmation_statement_overdue',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Confirmation Statement Overdue'),
        ),
        migrations.AlterField(
            model_name='companyhousedata',
            name='has_been_liquidated',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Has Been Liquidated'),
        ),
        migrations.AlterField(
            model_name='companyhousedata',
            name='has_charges',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Has Charges'),
        ),
        migrations.AlterField(
            model_name='companyhousedata',
            name='has_insolvency_history',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Has Insolvency History'),
        ),
        migrations.AlterField(
            model_name='companyhousedata',
            name='officers_active_count',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Officers Active Count'),
        ),
        migrations.AlterField(
            model_name='companyhousedata',
            name='officers_inactive_count',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Officers Inactive Count'),
        ),
        migrations.AlterField(
            model_name='companyhousedata',
            name='officers_resigned_count',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Officers Resigned Count'),
        ),
        migrations.AlterField(
            model_name='companyhousedata',
            name='officers_total_count',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Officers Total Count'),
        ),
        migrations.AlterField(
            model_name='companyhousedata',
            name='registered_office_is_in_dispute',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Registered Office Is In Dispute'),
        ),
        migrations.AlterField(
            model_name='companyhousedata',
            name='undeliverable_registered_office_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Undeliverable Registered Office Address'),
        ),
    ]
