# Generated by Django 5.1.11 on 2025-08-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_increase_field_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text="Keyword to search for on company websites (e.g., 'privacy policy')", max_length=255, unique=True, verbose_name='Search Keyword')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Search Keyword',
                'verbose_name_plural': 'Search Keywords',
                'ordering': ['keyword'],
            },
        ),
    ]
