# Generated by Django 5.1.11 on 2025-08-12 23:40

from django.db import migrations


def add_default_search_keywords(apps, schema_editor):
    """Add default search keywords to the database."""
    SearchKeyword = apps.get_model('portal', 'SearchKeyword')
    
    default_keywords = [
        "privacy policy",
        "terms",
        "about us", 
        "company number",
        "company information"
    ]
    
    for keyword in default_keywords:
        SearchKeyword.objects.get_or_create(keyword=keyword)


def remove_default_search_keywords(apps, schema_editor):
    """Remove default search keywords from the database."""
    SearchKeyword = apps.get_model('portal', 'SearchKeyword')
    
    default_keywords = [
        "privacy policy",
        "terms",
        "about us", 
        "company number",
        "company information"
    ]
    
    SearchKeyword.objects.filter(keyword__in=default_keywords).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_add_search_keywords'),
    ]

    operations = [
        migrations.RunPython(add_default_search_keywords, remove_default_search_keywords),
    ]
