# Generated by Django 5.1.11 on 2025-08-15 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_add_approved_domain_to_website_hunting_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContactLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_searched', models.CharField(help_text='The domain that was searched for contact information', max_length=255, verbose_name='Domain Searched')),
                ('phone_numbers', models.JSONField(default=list, help_text='List of phone numbers found on the website', verbose_name='Phone Numbers')),
                ('email_addresses', models.JSONField(default=list, help_text='List of email addresses found on the website', verbose_name='Email Addresses')),
                ('social_media_links', models.JSONField(default=dict, help_text='Social media links found (Facebook, Instagram, LinkedIn)', verbose_name='Social Media Links')),
                ('status', models.CharField(help_text='Status of the contact extraction process', max_length=50, verbose_name='Status')),
                ('processing_notes', models.TextField(help_text='Notes about the contact extraction process', verbose_name='Processing Notes')),
                ('pages_crawled', models.PositiveIntegerField(default=0, help_text='Number of pages crawled during extraction', verbose_name='Pages Crawled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('company_number', models.OneToOneField(help_text='The company number this contact lookup belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='website_contact_lookup', to='portal.companynumber')),
            ],
            options={
                'verbose_name': 'Website Contact Lookup',
                'verbose_name_plural': 'Website Contact Lookups',
                'ordering': ['-created_at'],
            },
        ),
    ]
