# Generated by Django 5.1.11 on 2025-08-15 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_websitecontactlookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='linkedin_lookup_enabled',
            field=models.BooleanField(default=False, help_text='Whether LinkedIn lookup is enabled for this campaign', verbose_name='LinkedIn Lookup Enabled'),
        ),
        migrations.CreateModel(
            name='LinkedinLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_urls', models.JSONField(default=list, help_text='List of LinkedIn company profile URLs found', verbose_name='Company URLs')),
                ('employee_urls', models.JSONField(default=list, help_text='List of LinkedIn employee profile URLs found', verbose_name='Employee URLs')),
                ('search_query', models.TextField(help_text='The query used for LinkedIn search', verbose_name='Search Query')),
                ('search_status', models.CharField(help_text='Status of the LinkedIn search process', max_length=50, verbose_name='Search Status')),
                ('processing_notes', models.TextField(help_text='Notes about the LinkedIn search process', verbose_name='Processing Notes')),
                ('total_results_found', models.PositiveIntegerField(default=0, help_text='Total number of LinkedIn profiles found', verbose_name='Total Results Found')),
                ('approved_domain_used', models.CharField(blank=True, help_text='The approved domain that was used for enhanced search', max_length=255, null=True, verbose_name='Approved Domain Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('company_number', models.OneToOneField(help_text='The company number this LinkedIn lookup belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_lookup', to='portal.companynumber')),
            ],
            options={
                'verbose_name': 'LinkedIn Lookup',
                'verbose_name_plural': 'LinkedIn Lookups',
                'ordering': ['-created_at'],
            },
        ),
    ]
