# Generated by Django 5.1.11 on 2025-09-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_campaign_linkedin_lookup_enabled_linkedinlookup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='linkedin_lookup_enabled',
        ),
    ]
