# Generated by Django 5.1.11 on 2025-09-03 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_remove_linkedin_lookup_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinEmployeeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_employee_urls', models.JSONField(default=list, help_text='List of approved LinkedIn employee profile URLs with metadata', verbose_name='Approved Employee URLs')),
                ('source_breakdown', models.JSONField(default=dict, help_text='Statistics about URL sources (website vs linkedin discovery)', verbose_name='Source Breakdown')),
                ('review_status', models.CharField(default='PENDING', help_text='Status of the LinkedIn employee review process', max_length=50, verbose_name='Review Status')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the review was completed', null=True, verbose_name='Reviewed At')),
                ('total_urls_found', models.PositiveIntegerField(default=0, help_text='Total number of LinkedIn employee URLs found from both sources', verbose_name='Total URLs Found')),
                ('total_approved', models.PositiveIntegerField(default=0, help_text='Total number of employee URLs approved by human review', verbose_name='Total Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('company_number', models.OneToOneField(help_text='The company number this LinkedIn employee review belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_employee_review', to='portal.companynumber')),
            ],
            options={
                'verbose_name': 'LinkedIn Employee Review',
                'verbose_name_plural': 'LinkedIn Employee Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
