# Generated by Django 5.1.11 on 2025-09-04 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_linkedinemployeereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnovQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_credits', models.DecimalField(decimal_places=2, default=0.0, help_text='Number of available Snov.io API credits', max_digits=12, verbose_name='Available Credits')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When the quota was last updated', verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Snov Quota',
                'verbose_name_plural': 'Snov Quota',
            },
        ),
        migrations.AlterModelOptions(
            name='linkedinemployeereview',
            options={'ordering': ['-reviewed_at'], 'verbose_name': 'LinkedIn Employee Review', 'verbose_name_plural': 'LinkedIn Employee Reviews'},
        ),
        migrations.RemoveField(
            model_name='linkedinemployeereview',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='linkedinemployeereview',
            name='review_status',
        ),
        migrations.RemoveField(
            model_name='linkedinemployeereview',
            name='source_breakdown',
        ),
        migrations.RemoveField(
            model_name='linkedinemployeereview',
            name='total_approved',
        ),
        migrations.RemoveField(
            model_name='linkedinemployeereview',
            name='total_urls_found',
        ),
        migrations.AlterField(
            model_name='linkedinemployeereview',
            name='reviewed_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 4, 7, 12, 33, 341999, tzinfo=datetime.timezone.utc), help_text='When the review was completed', verbose_name='Reviewed At'),
            preserve_default=False,
        ),
    ]
