# Generated by Django 5.1.11 on 2025-09-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_snovlookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='HunterQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_credits', models.DecimalField(decimal_places=2, default=0.0, help_text='Number of available Hunter.io API credits (available - used)', max_digits=12, verbose_name='Available Credits')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When the quota was last updated', verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Hunter Quota',
                'verbose_name_plural': 'Hunter Quota',
            },
        ),
    ]
