# Generated by Django 5.1.11 on 2025-09-08 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_hunterquota'),
    ]

    operations = [
        migrations.CreateModel(
            name='HunterLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_searched', models.CharField(help_text='The approved domain that was searched', max_length=255, verbose_name='Domain Searched')),
                ('emails_found', models.JSONField(default=list, help_text='List of email addresses found with their details', verbose_name='Emails Found')),
                ('processing_status', models.CharField(choices=[('SUCCESS', 'Success'), ('NO_EMAILS_FOUND', 'No Emails Found'), ('API_ERROR', 'API Error'), ('PROCESSING_ERROR', 'Processing Error')], default='SUCCESS', help_text='Overall status of the Hunter.io processing', max_length=50, verbose_name='Processing Status')),
                ('processing_notes', models.TextField(blank=True, help_text='Additional notes about the processing, including any errors or warnings', verbose_name='Processing Notes')),
                ('total_emails_found', models.PositiveIntegerField(default=0, help_text='Total number of email addresses found for this domain', verbose_name='Total Emails Found')),
                ('processed_at', models.DateTimeField(auto_now_add=True, help_text='When the Hunter.io processing was completed', verbose_name='Processed At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated', verbose_name='Updated At')),
                ('company_number', models.OneToOneField(help_text='The company number this Hunter lookup belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='hunter_lookup', to='portal.companynumber')),
            ],
            options={
                'verbose_name': 'Hunter Lookup',
                'verbose_name_plural': 'Hunter Lookups',
                'ordering': ['-processed_at'],
            },
        ),
    ]
